import "./globals.scss";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import NavigationEvents from "@/components/NavigationEvents";

const roboto = Roboto({
  weight: ["400", "500", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "NextJS Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        <NavigationEvents />
      </body>
    </html>
  );
}
